// Builds a clean, shareable PDF of a meeting's notes entirely in the webview,
// then returns it as standard base64 for the Rust side to save / attach. Vector
// text (not a screenshot) so it stays crisp and small.
import { jsPDF } from "jspdf";
import type { NoteDetail } from "./ipc";

function fmtDate(ms: number): string {
  return new Date(ms).toLocaleString(undefined, {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

const INDIGO: [number, number, number] = [79, 70, 229];
const INK: [number, number, number] = [26, 24, 35];
const MUTED: [number, number, number] = [110, 110, 125];

const MARGIN = 56;
const PAGE_W = 595.28; // A4 pt
const PAGE_H = 841.89;
const CONTENT_W = PAGE_W - MARGIN * 2;

function modelLabel(model: string): string {
  if (model === "gpt-4o-mini") return "GPT-4o mini";
  if (model === "gpt-4o") return "GPT-4o";
  return model || "GPT-4o";
}

export function buildNotePdfBase64(note: NoteDetail): string {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const g = note.generated;
  let y = MARGIN;

  const ensure = (need: number) => {
    if (y + need > PAGE_H - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  };

  // Title + date.
  doc.setTextColor(...INK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  const titleLines = doc.splitTextToSize(note.title.trim() || "Untitled meeting", CONTENT_W);
  for (const line of titleLines) {
    ensure(26);
    doc.text(line, MARGIN, y);
    y += 26;
  }
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...MUTED);
  ensure(20);
  doc.text(fmtDate(note.createdAt), MARGIN, y);
  y += 24;

  const heading = (label: string) => {
    ensure(34);
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...INDIGO);
    doc.text(label, MARGIN, y);
    y += 18;
  };

  const paragraph = (text: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(...INK);
    const lines = doc.splitTextToSize(text, CONTENT_W);
    for (const line of lines) {
      ensure(16);
      doc.text(line, MARGIN, y);
      y += 16;
    }
  };

  const bullets = (items: string[]) => {
    doc.setFontSize(11);
    for (const item of items) {
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...INK);
      const lines = doc.splitTextToSize(item, CONTENT_W - 16);
      lines.forEach((line: string, i: number) => {
        ensure(16);
        if (i === 0) {
          doc.setTextColor(...INDIGO);
          doc.text("•", MARGIN, y);
          doc.setTextColor(...INK);
        }
        doc.text(line, MARGIN + 16, y);
        y += 16;
      });
      y += 2;
    }
  };

  if (g?.summary) {
    heading("Summary");
    paragraph(g.summary);
  }
  if (g && g.keyPoints.length) {
    heading("Key points");
    bullets(g.keyPoints);
  }
  if (g && g.decisions.length) {
    heading("Decisions");
    bullets(g.decisions);
  }
  if (g && g.openQuestions.length) {
    heading("Open questions");
    bullets(g.openQuestions);
  }
  if (note.actionItems.length) {
    heading("Action items");
    bullets(
      note.actionItems.map((a) => {
        let t = a.text;
        if (a.assignee) t += `  —  ${a.assignee}`;
        if (a.dueHint) t += `  (due ${a.dueHint})`;
        return t;
      })
    );
  }
  if (note.scratch.trim()) {
    heading("Your notes");
    paragraph(note.scratch.trim());
  }

  // Footer on the last page.
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  const foot = g?.model
    ? `Generated by Glyph · proofread & summarized by ${modelLabel(g.model)}`
    : "Generated by Glyph";
  doc.text(foot, MARGIN, PAGE_H - 30);

  // datauristring → strip the "data:application/pdf;base64," prefix.
  const uri = doc.output("datauristring");
  return uri.slice(uri.indexOf(",") + 1);
}
