//! NotesStore commands (SPEC §11) — SQLite-backed persistence for notes,
//! transcript segments, generated notes, and action items. Wired in M4 so the
//! full record → transcript → notes → reopen loop survives quit/relaunch.

use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

use base64::Engine;
use rusqlite::params;
use serde::{Deserialize, Serialize};
use tauri::State;

use crate::commands::Db;

fn now_ms() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

fn new_id() -> String {
    let mut b = [0u8; 12];
    let _ = getrandom::getrandom(&mut b);
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(b)
}

/// Per-meeting export folder. Each note gets readable local files (transcript +
/// notes markdown) alongside the SQLite copy, so nothing is locked inside the DB
/// and the full verbatim transcript is always recoverable from disk.
fn meeting_dir(note_id: &str) -> Option<PathBuf> {
    let home = std::env::var_os("HOME")?;
    Some(
        PathBuf::from(home)
            .join("Library/Application Support/ai.oltaflock.glyph/meetings")
            .join(note_id),
    )
}

fn fmt_ts(ms: i64) -> String {
    let total = (ms / 1000).max(0);
    format!("{}:{:02}", total / 60, total % 60)
}

/// Write the full verbatim transcript to `meetings/<id>/transcript.txt`. Best
/// effort — failures never block the DB write.
fn export_transcript(conn: &rusqlite::Connection, note_id: &str, segments: &[SegmentIn]) {
    let Some(dir) = meeting_dir(note_id) else { return };
    if std::fs::create_dir_all(&dir).is_err() {
        return;
    }
    let title: String = conn
        .query_row("SELECT title FROM notes WHERE id = ?1", params![note_id], |r| r.get(0))
        .unwrap_or_default();
    let heading = if title.trim().is_empty() { "Untitled meeting" } else { title.trim() };
    let mut out = format!("{heading} — transcript\n\n");
    if segments.is_empty() {
        out.push_str("(no speech transcribed)\n");
    } else {
        for s in segments {
            let lang = if s.lang.is_empty() { String::new() } else { format!(" ({})", s.lang) };
            out.push_str(&format!("[{}–{}]{} {}\n", fmt_ts(s.start_ms), fmt_ts(s.end_ms), lang, s.text));
        }
    }
    let _ = std::fs::write(dir.join("transcript.txt"), out);
}

/// Write the generated notes to `meetings/<id>/notes.md`. Best effort.
#[allow(clippy::too_many_arguments)]
fn export_notes_md(
    conn: &rusqlite::Connection,
    note_id: &str,
    summary: &str,
    key_points: &[String],
    decisions: &[String],
    open_questions: &[String],
    action_items: &[ActionItemIn],
    model: &str,
) {
    let Some(dir) = meeting_dir(note_id) else { return };
    if std::fs::create_dir_all(&dir).is_err() {
        return;
    }
    let (title, scratch): (String, String) = conn
        .query_row("SELECT title, scratch FROM notes WHERE id = ?1", params![note_id], |r| {
            Ok((r.get(0)?, r.get(1)?))
        })
        .unwrap_or_default();
    let heading = if title.trim().is_empty() { "Untitled meeting" } else { title.trim() };
    let mut m = format!("# {heading}\n\n");
    if !summary.trim().is_empty() {
        m.push_str(&format!("## Summary\n\n{}\n\n", summary.trim()));
    }
    let section = |m: &mut String, label: &str, items: &[String]| {
        if !items.is_empty() {
            m.push_str(&format!("## {label}\n\n"));
            for i in items {
                m.push_str(&format!("- {i}\n"));
            }
            m.push('\n');
        }
    };
    section(&mut m, "Key points", key_points);
    section(&mut m, "Decisions", decisions);
    section(&mut m, "Open questions", open_questions);
    if !action_items.is_empty() {
        m.push_str("## Action items\n\n");
        for a in action_items {
            let mut line = format!("- [ ] {}", a.text);
            if let Some(who) = a.assignee.as_deref().filter(|s| !s.is_empty()) {
                line.push_str(&format!(" — **{who}**"));
            }
            if let Some(due) = a.due_hint.as_deref().filter(|s| !s.is_empty()) {
                line.push_str(&format!(" _(due {due})_"));
            }
            m.push_str(&line);
            m.push('\n');
        }
        m.push('\n');
    }
    if !scratch.trim().is_empty() {
        m.push_str(&format!("## Your notes\n\n{}\n\n", scratch.trim()));
    }
    m.push_str(&format!("---\n_Generated by {model}._\n"));
    let _ = std::fs::write(dir.join("notes.md"), m);
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteSummary {
    id: String,
    title: String,
    created_at: i64,
    updated_at: i64,
    source: String,
    status: String,
    action_item_count: i64,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SegmentRow {
    text: String,
    lang: String,
    start_ms: i64,
    end_ms: i64,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ActionItemRow {
    id: String,
    text: String,
    assignee: Option<String>,
    due_hint: Option<String>,
    source: String,
    asana_gid: Option<String>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GeneratedStored {
    summary: String,
    key_points: Vec<String>,
    decisions: Vec<String>,
    open_questions: Vec<String>,
    model: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteDetail {
    id: String,
    title: String,
    created_at: i64,
    updated_at: i64,
    source: String,
    status: String,
    scratch: String,
    duration_sec: i64,
    audio_path: Option<String>,
    segments: Vec<SegmentRow>,
    generated: Option<GeneratedStored>,
    action_items: Vec<ActionItemRow>,
}

#[derive(Deserialize)]
pub struct SegmentIn {
    pub text: String,
    #[serde(default)]
    pub lang: String,
    #[serde(default, rename = "startMs", alias = "start_ms")]
    pub start_ms: i64,
    #[serde(default, rename = "endMs", alias = "end_ms")]
    pub end_ms: i64,
}

#[derive(Deserialize)]
pub struct ActionItemIn {
    pub text: String,
    pub assignee: Option<String>,
    #[serde(rename = "dueHint", alias = "due_hint")]
    pub due_hint: Option<String>,
}

#[tauri::command]
pub fn create_note(db: State<'_, Db>, source: String, title: Option<String>) -> Result<String, String> {
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    let id = new_id();
    let ts = now_ms();
    conn.execute(
        "INSERT INTO notes (id, title, created_at, updated_at, source, status) VALUES (?1,?2,?3,?3,?4,'draft')",
        params![id, title.unwrap_or_default(), ts, source],
    )
    .map_err(|e| e.to_string())?;
    Ok(id)
}

#[tauri::command]
pub fn list_notes(db: State<'_, Db>) -> Result<Vec<NoteSummary>, String> {
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    let mut stmt = conn
        .prepare(
            "SELECT n.id, n.title, n.created_at, n.updated_at, n.source, n.status,
                    (SELECT COUNT(*) FROM action_items a WHERE a.note_id = n.id)
             FROM notes n ORDER BY n.updated_at DESC",
        )
        .map_err(|e| e.to_string())?;
    let rows = stmt
        .query_map([], |r| {
            Ok(NoteSummary {
                id: r.get(0)?,
                title: r.get(1)?,
                created_at: r.get(2)?,
                updated_at: r.get(3)?,
                source: r.get(4)?,
                status: r.get(5)?,
                action_item_count: r.get(6)?,
            })
        })
        .map_err(|e| e.to_string())?;
    rows.collect::<Result<_, _>>().map_err(|e| e.to_string())
}

#[tauri::command]
pub fn get_note(db: State<'_, Db>, id: String) -> Result<NoteDetail, String> {
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    let (title, created_at, updated_at, source, status, scratch, duration_sec, audio_path) = conn
        .query_row(
            "SELECT title, created_at, updated_at, source, status, scratch, duration_sec, audio_path FROM notes WHERE id = ?1",
            params![id],
            |r| {
                Ok((
                    r.get::<_, String>(0)?,
                    r.get::<_, i64>(1)?,
                    r.get::<_, i64>(2)?,
                    r.get::<_, String>(3)?,
                    r.get::<_, String>(4)?,
                    r.get::<_, String>(5)?,
                    r.get::<_, i64>(6)?,
                    r.get::<_, Option<String>>(7)?,
                ))
            },
        )
        .map_err(|e| e.to_string())?;

    let mut seg_stmt = conn
        .prepare("SELECT text, lang, start_ms, end_ms FROM segments WHERE note_id = ?1 ORDER BY idx")
        .map_err(|e| e.to_string())?;
    let segments = seg_stmt
        .query_map(params![id], |r| {
            Ok(SegmentRow {
                text: r.get(0)?,
                lang: r.get::<_, Option<String>>(1)?.unwrap_or_default(),
                start_ms: r.get(2)?,
                end_ms: r.get(3)?,
            })
        })
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;

    let generated = conn
        .query_row(
            "SELECT markdown, model FROM generated_notes WHERE note_id = ?1",
            params![id],
            |r| Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?)),
        )
        .ok()
        .and_then(|(json, model)| {
            serde_json::from_str::<serde_json::Value>(&json).ok().map(|v| GeneratedStored {
                summary: v.get("summary").and_then(|s| s.as_str()).unwrap_or("").to_string(),
                key_points: v
                    .get("keyPoints")
                    .and_then(|k| k.as_array())
                    .map(|a| a.iter().filter_map(|x| x.as_str().map(String::from)).collect())
                    .unwrap_or_default(),
                decisions: v
                    .get("decisions")
                    .and_then(|k| k.as_array())
                    .map(|a| a.iter().filter_map(|x| x.as_str().map(String::from)).collect())
                    .unwrap_or_default(),
                open_questions: v
                    .get("openQuestions")
                    .and_then(|k| k.as_array())
                    .map(|a| a.iter().filter_map(|x| x.as_str().map(String::from)).collect())
                    .unwrap_or_default(),
                model,
            })
        });

    let mut ai_stmt = conn
        .prepare("SELECT id, text, assignee, due_hint, source, asana_gid FROM action_items WHERE note_id = ?1 ORDER BY rowid")
        .map_err(|e| e.to_string())?;
    let action_items = ai_stmt
        .query_map(params![id], |r| {
            Ok(ActionItemRow {
                id: r.get(0)?,
                text: r.get(1)?,
                assignee: r.get(2)?,
                due_hint: r.get(3)?,
                source: r.get(4)?,
                asana_gid: r.get(5)?,
            })
        })
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())?;

    Ok(NoteDetail {
        id,
        title,
        created_at,
        updated_at,
        source,
        status,
        scratch,
        duration_sec,
        audio_path,
        segments,
        generated,
        action_items,
    })
}

fn touch(conn: &rusqlite::Connection, id: &str) {
    let _ = conn.execute("UPDATE notes SET updated_at = ?2 WHERE id = ?1", params![id, now_ms()]);
}

#[tauri::command]
pub fn update_title(db: State<'_, Db>, id: String, title: String) -> Result<(), String> {
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    conn.execute("UPDATE notes SET title = ?2, updated_at = ?3 WHERE id = ?1", params![id, title, now_ms()])
        .map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
pub fn save_scratch(db: State<'_, Db>, id: String, scratch: String) -> Result<(), String> {
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    conn.execute("UPDATE notes SET scratch = ?2, updated_at = ?3 WHERE id = ?1", params![id, scratch, now_ms()])
        .map_err(|e| e.to_string())?;
    Ok(())
}

/// Replace all transcript segments for a note (called after a recording stops).
#[tauri::command]
pub fn save_segments(db: State<'_, Db>, note_id: String, segments: Vec<SegmentIn>) -> Result<(), String> {
    let mut conn = db.0.lock().map_err(|e| e.to_string())?;
    let tx = conn.transaction().map_err(|e| e.to_string())?;
    // Safety net: never lose a recording because the note row is missing
    // (deleted, or createNote failed). Recreate it idempotently.
    tx.execute(
        "INSERT OR IGNORE INTO notes (id, title, created_at, updated_at, source, status) VALUES (?1, '', ?2, ?2, 'recorded', 'draft')",
        params![note_id, now_ms()],
    )
    .map_err(|e| e.to_string())?;
    tx.execute("DELETE FROM segments WHERE note_id = ?1", params![note_id])
        .map_err(|e| e.to_string())?;
    for (i, s) in segments.iter().enumerate() {
        tx.execute(
            "INSERT INTO segments (id, note_id, idx, start_ms, end_ms, text, lang) VALUES (?1,?2,?3,?4,?5,?6,?7)",
            params![new_id(), note_id, i as i64, s.start_ms, s.end_ms, s.text, s.lang],
        )
        .map_err(|e| e.to_string())?;
    }
    touch(&tx, &note_id);
    tx.commit().map_err(|e| e.to_string())?;
    export_transcript(&conn, &note_id, &segments);
    Ok(())
}

/// Persist the generated note + its AI action items (replacing prior AI items).
#[tauri::command]
#[allow(clippy::too_many_arguments)]
pub fn save_generated(
    db: State<'_, Db>,
    note_id: String,
    summary: String,
    key_points: Vec<String>,
    decisions: Vec<String>,
    open_questions: Vec<String>,
    action_items: Vec<ActionItemIn>,
    model: String,
) -> Result<(), String> {
    let mut conn = db.0.lock().map_err(|e| e.to_string())?;
    let json = serde_json::json!({
        "summary": summary, "keyPoints": key_points, "decisions": decisions,
        "openQuestions": open_questions, "model": model
    })
    .to_string();
    let tx = conn.transaction().map_err(|e| e.to_string())?;
    tx.execute(
        "INSERT OR IGNORE INTO notes (id, title, created_at, updated_at, source, status) VALUES (?1, '', ?2, ?2, 'recorded', 'draft')",
        params![note_id, now_ms()],
    )
    .map_err(|e| e.to_string())?;
    tx.execute("DELETE FROM generated_notes WHERE note_id = ?1", params![note_id])
        .map_err(|e| e.to_string())?;
    tx.execute(
        "INSERT INTO generated_notes (note_id, markdown, model, generated_at) VALUES (?1,?2,?3,?4)",
        params![note_id, json, model, now_ms()],
    )
    .map_err(|e| e.to_string())?;
    tx.execute("DELETE FROM action_items WHERE note_id = ?1 AND source = 'ai'", params![note_id])
        .map_err(|e| e.to_string())?;
    for a in &action_items {
        tx.execute(
            "INSERT INTO action_items (id, note_id, text, assignee, due_hint, source) VALUES (?1,?2,?3,?4,?5,'ai')",
            params![new_id(), note_id, a.text, a.assignee, a.due_hint],
        )
        .map_err(|e| e.to_string())?;
    }
    tx.execute("UPDATE notes SET status = 'ready', updated_at = ?2 WHERE id = ?1", params![note_id, now_ms()])
        .map_err(|e| e.to_string())?;
    tx.commit().map_err(|e| e.to_string())?;
    export_notes_md(&conn, &note_id, &summary, &key_points, &decisions, &open_questions, &action_items, &model);
    Ok(())
}

/// A filesystem-safe slug from a meeting title (for PDF filenames).
fn slugify(title: &str) -> String {
    let s: String = title
        .trim()
        .chars()
        .map(|c| if c.is_alphanumeric() { c.to_ascii_lowercase() } else { '-' })
        .collect();
    let s = s.trim_matches('-').replace("--", "-");
    let s: String = s.chars().take(60).collect();
    if s.trim_matches('-').is_empty() { "meeting".into() } else { s }
}

/// Write a PDF (built in the webview, passed as standard base64) into the
/// meeting folder and open it. Returns the file path.
#[tauri::command]
pub fn save_note_pdf(db: State<'_, Db>, note_id: String, pdf_base64: String) -> Result<String, String> {
    let title: String = {
        let conn = db.0.lock().map_err(|e| e.to_string())?;
        conn.query_row("SELECT title FROM notes WHERE id = ?1", params![note_id], |r| r.get(0))
            .unwrap_or_default()
    };
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(pdf_base64.trim())
        .map_err(|e| format!("bad PDF data: {e}"))?;
    let dir = meeting_dir(&note_id).ok_or("no home directory")?;
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    let path = dir.join(format!("{}-notes.pdf", slugify(&title)));
    std::fs::write(&path, bytes).map_err(|e| e.to_string())?;
    let _ = std::process::Command::new("open").arg(&path).spawn();
    Ok(path.to_string_lossy().into_owned())
}

/// Open the meeting's local-files folder (transcript.txt + notes.md) in Finder.
#[tauri::command]
pub fn reveal_note_files(id: String) -> Result<String, String> {
    let dir = meeting_dir(&id).ok_or("no home directory")?;
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    std::process::Command::new("open")
        .arg(&dir)
        .spawn()
        .map_err(|e| e.to_string())?;
    Ok(dir.to_string_lossy().into_owned())
}

#[tauri::command]
pub fn add_action_item(
    db: State<'_, Db>,
    note_id: String,
    text: String,
    assignee: Option<String>,
    due_hint: Option<String>,
) -> Result<String, String> {
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    let id = new_id();
    conn.execute(
        "INSERT INTO action_items (id, note_id, text, assignee, due_hint, source) VALUES (?1,?2,?3,?4,?5,'manual')",
        params![id, note_id, text, assignee, due_hint],
    )
    .map_err(|e| e.to_string())?;
    touch(&conn, &note_id);
    Ok(id)
}

#[tauri::command]
pub fn delete_action_item(db: State<'_, Db>, id: String) -> Result<(), String> {
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    conn.execute("DELETE FROM action_items WHERE id = ?1", params![id])
        .map_err(|e| e.to_string())?;
    Ok(())
}

/// True recording length from a 16 kHz mono 16-bit WAV: data bytes / byte-rate.
/// This is ground truth — unlike the frontend's wall-clock tick counter, which
/// WebKit throttles when Glyph is backgrounded during a call (a long meeting
/// would otherwise report roughly half its real length).
fn wav_duration_secs(path: &str) -> Option<i64> {
    use std::io::Read;
    let mut f = std::fs::File::open(path).ok()?;
    let mut header = [0u8; 44];
    f.read_exact(&mut header).ok()?;
    // byte_rate is bytes 28..32 of a canonical WAV header.
    let byte_rate = u32::from_le_bytes([header[28], header[29], header[30], header[31]]);
    if byte_rate == 0 {
        return None;
    }
    let total = std::fs::metadata(path).ok()?.len();
    if total <= 44 {
        return Some(0);
    }
    Some(((total - 44) / u64::from(byte_rate)) as i64)
}

/// Record audio/duration/status after a recording stops. The duration is taken
/// from the saved WAV when available (accurate), falling back to the value the
/// frontend timed.
#[tauri::command]
pub fn set_recording_result(
    db: State<'_, Db>,
    id: String,
    audio_path: Option<String>,
    duration_sec: i64,
) -> Result<(), String> {
    let duration = audio_path
        .as_deref()
        .and_then(wav_duration_secs)
        .filter(|d| *d > 0)
        .unwrap_or(duration_sec);
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    conn.execute(
        "INSERT INTO notes (id, title, created_at, updated_at, source, status, audio_path, duration_sec)
         VALUES (?1, '', ?4, ?4, 'recorded', 'draft', ?2, ?3)
         ON CONFLICT(id) DO UPDATE SET audio_path = ?2, duration_sec = ?3, updated_at = ?4",
        params![id, audio_path, duration, now_ms()],
    )
    .map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
pub fn delete_note(db: State<'_, Db>, id: String) -> Result<(), String> {
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    // remove audio file if present
    if let Ok(Some(path)) = conn.query_row(
        "SELECT audio_path FROM notes WHERE id = ?1",
        params![id],
        |r| r.get::<_, Option<String>>(0),
    ) {
        let _ = std::fs::remove_file(path);
    }
    conn.execute("DELETE FROM notes WHERE id = ?1", params![id])
        .map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
pub fn delete_audio(db: State<'_, Db>, id: String) -> Result<(), String> {
    let conn = db.0.lock().map_err(|e| e.to_string())?;
    if let Ok(Some(path)) = conn.query_row(
        "SELECT audio_path FROM notes WHERE id = ?1",
        params![id],
        |r| r.get::<_, Option<String>>(0),
    ) {
        let _ = std::fs::remove_file(path);
    }
    conn.execute("UPDATE notes SET audio_path = NULL, updated_at = ?2 WHERE id = ?1", params![id, now_ms()])
        .map_err(|e| e.to_string())?;
    Ok(())
}
